version: "3.4"
# This compose file is for testing our example Apache configuration locally.
# To test you have to add `127.0.0.1 example.localhost` to your /etc/hosts.
services:
  apache:
    build:
      context: .
    ports:
      - '80:80'
    depends_on: [fwego]
  fwego:
    image: digitranslab/fwego:develop-latest
    environment:
      # Apache is configured to use the docker network to reach this Fwego service.
      # No need to use FWEGO_EXTRA_ALLOWED_HOSTS if your Apache can access your
      # Fwego normally on a port.
      FWEGO_EXTRA_ALLOWED_HOSTS: "fwego"
      FWEGO_PUBLIC_URL: http://example.localhost
    volumes:
      - fwego_data:/fwego/data
volumes:
  fwego_data:
