# Generated by Django 4.2.13 on 2024-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integrations",
            "0006_migrate_local_fwego_table_service_filter_formulas_to_value_is_formula",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="localfwegotableservicefieldmapping",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the field mapping is enabled. If it is disabled, we will not use the `value` when creating and updating rows.",
                null=True,
            ),
        ),
    ]
