version: "3.4"
services:
  {{ cookiecutter.project_slug }}:
    container_name: {{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      FWEGO_PUBLIC_URL: http://localhost
    volumes:
      - fwego_data:/fwego/data
volumes:
  fwego_data:
