{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwego.fullname" . }}
  namespace: {{ include "fwego.namespace" . }}
  labels:
    {{- include "fwego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fwego.selectorLabels" . | nindent 4 }}
{{- end }}
