version: "3.4"
# This compose file is for testing our example Nginx configuration locally.
# To test you have to add `127.0.0.1 example.localhost` to your /etc/hosts and then run
# docker-compose up
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [ fwego ]
  fwego:
    image: digitranslab/fwego:develop-latest
    environment:
      # This nginx is configured to use the docker network to reach the Fwego service.
      # No need to use FWEGO_EXTRA_ALLOWED_HOSTS if your Nginx can access your
      # Fwego on a normal network using localhost/127.0.0.1 .
      FWEGO_EXTRA_ALLOWED_HOSTS: "fwego"
      FWEGO_PUBLIC_URL: http://example.localhost
    volumes:
      - fwego_data:/fwego/data
volumes:
  fwego_data:
