version: "3.4"
services:
  # A dev compose file for quickly setting up an all in one with hot code reloading
  fwego_all_in_one_dev:
    image: fwego_dev
    build:
      dockerfile: $PWD/deploy/all-in-one/dev.Dockerfile
      context: $PWD
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: $UID
        GID: $GID
    environment:
      EMAIL_SMTP: 'yes'
      EMAIL_SMTP_HOST: 'mailhog'
      EMAIL_SMTP_PORT: '1025'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - fwego_all_in_one_data:/fwego/data
      - $PWD/deploy/all-in-one/fwego.sh:/fwego.sh
      - $PWD/backend:/fwego/backend
      - $PWD/premium/backend/:/fwego/premium/backend
      - $PWD/enterprise/backend/:/fwego/enterprise/backend
      - $PWD/web-frontend:/fwego/web-frontend
      # Override the above mounts for node_modules so we use the node_modules built
      # directly into the image instead of whatever is on your local filesystem.
      - /fwego/web-frontend/node_modules
      - $PWD/premium/web-frontend/:/fwego/premium/web-frontend
      - $PWD/enterprise/web-frontend/:/fwego/enterprise/web-frontend

    stdin_open: true
    tty: true
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8025:8025" # web ui
volumes:
  fwego_all_in_one_data:
