version: "3.4"
services:
  fwego-pgautoupgrade:
    image: fwego-pgautoupgrade
    build:
      dockerfile: $PWD/deploy/all-in-one/pgautoupgrade.Dockerfile
      context: $PWD
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: $UID
        GID: $GID
    volumes:
      - fwego_all_in_one_data:/fwego/data
    stdin_open: true
    tty: true
volumes:
  fwego_all_in_one_data:
